# -*- coding: utf-8 -*-
"""Prompting Experi_GPT-OSS-20b and GPT-OSS-120b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-p49ycy1YJ6PvC7Sqp0gKnTgg0f9z7N
"""

!pip install "transformers>=5.2.0"
!pip install torch==2.10.0
!pip install triton==3.6.0
from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "openai/gpt-oss-20b"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype="auto",
    device_map="auto",
)

import pandas as pd
import re
import os
import csv
from google.colab import drive

try:
   drive.mount('/content/drive')
except ValueError:
   drive.mount('/content/drive', force_remount=True)

BASE_PATH = "" # path removed
INPUT_CSV = os.path.join(BASE_PATH, "iSarcasmEval-1400.csv")
df_input = pd.read_csv(INPUT_CSV)
sentences = df_input["Sentence"].astype(str).tolist()
print(f"Loaded {len(sentences)} sentences from CSV.")

model_name = "GPT-OSS-20"
test = "zero" # Replace with "zero+conservative" and "COT" and "COT+conservative"
filename = model_name + "_" + test + "_iSarcasmEval.csv"
print(filename)
filepath = BASE_PATH + model_name + "/"
print(filepath)
# Paths
BASE_PATH = filepath
raw_output_path = os.path.join(BASE_PATH, "Raw_" + filename)
table_output_path = os.path.join(BASE_PATH, "Table_" + filename)

# Load already processed sentences (if file exists)
processed_sentences = set()
if os.path.exists(table_output_path):
    with open(table_output_path, mode="r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            processed_sentences.add(row["Sentence"])

print(f"Found {len(processed_sentences)} previously processed sentences.")

# Open files in append mode
raw_file = open(raw_output_path, mode="a", newline="", encoding="utf-8-sig")
table_file = open(table_output_path, mode="a", newline="", encoding="utf-8-sig")

raw_writer = csv.writer(raw_file)
table_writer = csv.writer(table_file)

# If files are new, write headers
if os.path.getsize(raw_output_path) == 0:
    raw_writer.writerow(["Line"])
if os.path.getsize(table_output_path) == 0:
    table_writer.writerow(["Sentence", "Sarcasm Polarity", "Intensity Score"])

# Process sentences
for sentence in sentences:
    if sentence in processed_sentences:
        print(f"Skipping already processed: {sentence}")
        continue

    prompt = f"""Instruction: Determine whether the following input text expresses sarcasm, if it does, output 'sarcastic', otherwise, output 'non-sarcastic'.

Input: {sentence}

Output:"""
    messages = [{"role": "user", "content": prompt}]
    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=True,
    ).to(model.device)

    outputs = model.generate(**inputs, max_new_tokens=10000, temperature=1.0)
    reply = tokenizer.decode(outputs[0])

    if "<|channel|>final<|message|>" in reply:
      clean_reply = reply.split("<|channel|>final<|message|>")[-1].replace("<|return|>", "").strip()
      reply = clean_reply

    else:
      print("Could not find the final output channel. Raw output:")


    matches = re.findall(r"(sarcastic|non-sarcastic)", reply)
    polarity = matches[-1] if matches else "Unknown"


    score_match = re.search(r"(-?\d+)", reply)
    score = int(score_match.group(0)) if score_match else None

    # Save raw output immediately
    raw_writer.writerow([sentence])
    raw_writer.writerow([reply])
    raw_writer.writerow(["-"*20])
    raw_file.flush()

    # Save structured table row immediately
    table_writer.writerow([sentence, polarity, score])
    table_file.flush()

    print(f"Processed and saved: {sentence}")

raw_file.close()
table_file.close()